### ISSUE TITLE
writing to-do

### ISSUE THREAD

**Issue by kel-github** [kel-github/seqtest-writeup#4]
- [ ] online behavioural description
- [ ] put analysis of pilot data on fig share
- [ ] add data to e-space
- [ ] back up of code to github
- [ ] find missing fdvars reference
